### ISSUE TITLE
Fix examples/franka_pick_block_ray.py (multiple values for argument 'shape_props')

### ISSUE THREAD

**Issue by tabula-rosa** [iamlab-cmu/isaacgym-utils#26]
I'm getting an error when trying to run the `ray` via `examples/franka_pick_block_ray.py`:

```
(deleteme3) telee@iam-ronan:~/ws/isaacgym-utils$ python examples/franka_pick_block_ray.py 
/home/telee/envs/deleteme3/lib/python3.7/site-packages/ray/autoscaler/_private/cli_logger.py:61: FutureWarning: Not all Ray CLI dependencies were found. In Ray 1.4+, the Ray CLI, autoscaler, and dashboard will only be usable via `pip install 'ray[default]'`. Please update your install command.
  "update your install command.", FutureWarning)
WARNING:root:Failed to import geometry msgs in rigid_transformations.py.
WARNING:root:Failed to import ros dependencies in rigid_transforms.py
WARNING:root:autolab_core not installed as catkin package, RigidTransform ros methods will be unavailable
Importing module 'gym_37' (/home/telee/ws/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_37.so)
Setting GYM_USD_PLUG_INFO_PATH to /home/telee/ws/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json
PyTorch version 1.9.0+cu102
Device count 1
/home/telee/ws/isaacgym/python/isaacgym/_bindings/src/gymtorch
Using /home/telee/.cache/torch_extensions as PyTorch extensions root...
Emitting ninja build file /home/telee/.cache/torch_extensions/gymtorch/build.ninja...
Building extension module gymtorch...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] c++ -MMD -MF gymtorch.o.d -DTORCH_EXTENSION_NAME=gymtorch -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/telee/envs/deleteme3/lib/python3.7/site-packages/torch/include -isystem /home/telee/envs/deleteme3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/telee/envs/deleteme3/lib/python3.7/site-packages/torch/include/TH -isystem /home/telee/envs/deleteme3/lib/python3.7/site-packages/torch/include/THC -isystem /home/telee/envs/deleteme3/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -DTORCH_MAJOR=1 -DTORCH_MINOR=9 -c /home/telee/ws/isaacgym/python/isaacgym/_bindings/src/gymtorch/gymtorch.cpp -o gymtorch.o 
[2/2] c++ gymtorch.o -shared -L/home/telee/envs/deleteme3/lib/python3.7/site-packages/torch/lib -lc10 -ltorch_cpu -ltorch -ltorch_python -o gymtorch.so
Loading extension module gymtorch...
2021-08-22 16:45:51,834	INFO services.py:1247 -- View the Ray dashboard at http://127.0.0.1:8265
INFO:root:Starting parallel execution of 4 scenes.
(pid=17530) Importing module 'gym_37' (/home/telee/ws/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_37.so)
(pid=17530) Setting GYM_USD_PLUG_INFO_PATH to /home/telee/ws/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json
(pid=17530) WARNING:root:Failed to import geometry msgs in rigid_transformations.py.
(pid=17530) WARNING:root:Failed to import ros dependencies in rigid_transforms.py
(pid=17530) WARNING:root:autolab_core not installed as catkin package, RigidTransform ros methods will be unavailable
(pid=17532) Importing module 'gym_37' (/home/telee/ws/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_37.so)
(pid=17531) Importing module 'gym_37' (/home/telee/ws/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_37.so)
(pid=17529) WARNING:root:Failed to import geometry msgs in rigid_transformations.py.
(pid=17529) WARNING:root:Failed to import ros dependencies in rigid_transforms.py
(pid=17529) WARNING:root:autolab_core not installed as catkin package, RigidTransform ros methods will be unavailable
(pid=17529) Importing module 'gym_37' (/home/telee/ws/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_37.so)
(pid=17529) Setting GYM_USD_PLUG_INFO_PATH to /home/telee/ws/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json
(pid=17532) Setting GYM_USD_PLUG_INFO_PATH to /home/telee/ws/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json
(pid=17531) Setting GYM_USD_PLUG_INFO_PATH to /home/telee/ws/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json
(pid=17532) WARNING:root:Failed to import geometry msgs in rigid_transformations.py.
(pid=17532) WARNING:root:Failed to import ros dependencies in rigid_transforms.py
(pid=17532) WARNING:root:autolab_core not installed as catkin package, RigidTransform ros methods will be unavailable
(pid=17531) WARNING:root:Failed to import geometry msgs in rigid_transformations.py.
(pid=17531) WARNING:root:Failed to import ros dependencies in rigid_transforms.py
(pid=17531) WARNING:root:autolab_core not installed as catkin package, RigidTransform ros methods will be unavailable
(pid=17530) PyTorch version 1.9.0+cu102
(pid=17530) Device count 1
(pid=17530) /home/telee/ws/isaacgym/python/isaacgym/_bindings/src/gymtorch
(pid=17530) Using /home/telee/.cache/torch_extensions as PyTorch extensions root...
(pid=17532) PyTorch version 1.9.0+cu102
(pid=17532) Device count 1
(pid=17532) /home/telee/ws/isaacgym/python/isaacgym/_bindings/src/gymtorch
(pid=17532) Using /home/telee/.cache/torch_extensions as PyTorch extensions root...
(pid=17531) PyTorch version 1.9.0+cu102
(pid=17531) Device count 1
(pid=17531) /home/telee/ws/isaacgym/python/isaacgym/_bindings/src/gymtorch
(pid=17531) Using /home/telee/.cache/torch_extensions as PyTorch extensions root...
(pid=17529) PyTorch version 1.9.0+cu102
(pid=17529) Device count 1
(pid=17529) /home/telee/ws/isaacgym/python/isaacgym/_bindings/src/gymtorch
(pid=17529) Using /home/telee/.cache/torch_extensions as PyTorch extensions root...
(pid=17530) Emitting ninja build file /home/telee/.cache/torch_extensions/gymtorch/build.ninja...
(pid=17530) Building extension module gymtorch...
(pid=17530) Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
(pid=17530) ninja: no work to do.
(pid=17530) Loading extension module gymtorch...
(pid=17532) Loading extension module gymtorch...
(pid=17531) Loading extension module gymtorch...
(pid=17529) Loading extension module gymtorch...
(pid=17530) Physics Engine: FleX
(pid=17530) Physics Device: cuda:0
(pid=17530) GPU Pipeline: disabled
(pid=17532) Physics Engine: FleX
(pid=17532) Physics Device: cuda:0
(pid=17532) GPU Pipeline: disabled
(pid=17531) Physics Engine: FleX
(pid=17531) Physics Device: cuda:0
(pid=17531) GPU Pipeline: disabled
(pid=17529) Physics Engine: FleX
(pid=17529) Physics Device: cuda:0
(pid=17529) GPU Pipeline: disabled
Traceback (most recent call last):
  File "examples/franka_pick_block_ray.py", line 118, in <module>
    ray.get(results)
  File "/home/telee/envs/deleteme3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/home/telee/envs/deleteme3/lib/python3.7/site-packages/ray/worker.py", line 1564, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TypeError): ray::run_grasp_block_policy() (pid=17531, ip=128.2.179.120)
  File "python/ray/_raylet.pyx", line 534, in ray._raylet.execute_task
  File "/home/telee/envs/deleteme3/lib/python3.7/site-packages/ray/util/tracing/tracing_helper.py", line 330, in _function_with_tracing
    return function(*args, **kwargs)
  File "examples/franka_pick_block_ray.py", line 49, in run_grasp_block_policy
    scene, table, franka, block = construct_gym_scene()
  File "examples/franka_pick_block_ray.py", line 24, in construct_gym_scene
    asset_options=cfg['table']['asset_options']
  File "/home/telee/ws/isaacgym-utils/isaacgym_utils/assets/assets.py", line 391, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got multiple values for argument 'shape_props'
```

**Comment by Skylark0924** [comment]
@tabula-rosa Hi, I faced the same issue. Have you ever found the solution?
